# JDBC connection settings
url=hashicorp,kv/data/MySQL/DEV/onlinebookstore,url
username=hashicorp,kv/data/MySQL/DEV/onlinebookstore,username
password=hashicorp,kv/data/MySQL/DEV/onlinebookstore,password
driver=${driver}
logLevel=info
vault.addr=${vaultAddress}
vault.namespace=${vaultNS}
